name: multistream_real
publish_to: 'none'

description: MultiStream mobile RTMP broadcaster for Red5 Cloud testing.

version: 1.0.0+2

environment:
  sdk: '>=3.5.0 <4.0.0'
  flutter: '>=3.29.0'

dependencies:
  flutter:
    sdk: flutter

  rtmp_streaming: ^2.0.1
  permission_handler: ^12.0.1
  wakelock_plus: ^1.2.10
  cupertino_icons: ^1.0.8
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
